In [1]:
import tensorflow as tf
import os, sys

os.environ["CUDA_VISIBLE_DEVICES"]="-1"

## tf.tile
tf.tile()把tensor中的值重复。
比如下边的例子: `a`是一个3*1的tensor，按[2,3] tile之后，获得一个[6, 3]的tensor
* 在第一个d上(也就是Matrix a的行）重复2次；
* 在第二个d上(Matrix a的列)上重复3次。

In [7]:
with tf.Graph().as_default():
    a = tf.constant([[0], [1], [2]],name='a') 
    a = tf.Print(a, [a], message="a=")
    b = tf.tile(a, [2,3], name="tile")
    sess = tf.Session()
    print(sess.run(b))

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [0 0 0]
 [1 1 1]
 [2 2 2]]


## tf.reduce_sum
tf.reduce_sum是常用的求和操作。参数axis指定对哪一个d求和，相当于从结果中去掉某个dimension。如下面的例子：
```
a = [[
   [2,3,1], 
   [1,1,1] 
]]
```
shape=（1, 2,3）可以想象成一个魔方。

* axis=0的时候，去掉第一维，也就是从`[[2 3 1], [1 1 1]]`
* axis=1的时候，结果形状就是(1,3)，结果为`[[3 4 2]]`
* axis=2 形状为(1,2),结果为`[[6 3]]`

In [19]:
with tf.Graph().as_default():
    a = tf.constant([[[2,3,1], [1,1,1]]],name='a') 
    print(a.shape)
    b = tf.reduce_sum(a, axis=0)
    c = tf.reduce_sum(a, axis=1)
    d = tf.reduce_sum(a, axis=2)
    sess = tf.Session()
    print("tf.reduce_sum(a, axis=0): ")
    print(sess.run(b))
    print(b.shape)
    print("tf.reduce_sum(a, axis=1): ")
    print(sess.run(c))
    print(c.shape)
    print("tf.reduce_sum(a, axis=2): ")
    print(sess.run(d))
    print(d.shape)

(1, 2, 3)
tf.reduce_sum(a, axis=0): 
[[2 3 1]
 [1 1 1]]
(2, 3)
tf.reduce_sum(a, axis=1): 
[[3 4 2]]
(1, 3)
tf.reduce_sum(a, axis=2): 
[[6 3]]
(1, 2)
